/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Gui;

import Model.Artifacts.Armor;
import Model.Artifacts.Helm;
import Model.Artifacts.Weapon;
import Model.Characters.Hero;
import Model.Map;
import java.util.Random;

/**
 *
 * @author spencer
 */
public class SelectArtifact extends javax.swing.JPanel {

    private Map map;
    private Hero hero;
    private Random rand;
    private Helm helm = null;
    private Armor armor = null;
    private Weapon weapon = null;
    private int dropChance;

    /**
     * Creates new form HeroBattle
     */
    public SelectArtifact(Map map, Hero hero) {
        initComponents();
        this.map = map;
        this.hero = hero;
        rand = new Random();
        displayArtifact();
    }

    private void displayArtifact() {
        dropChance = rand.nextInt(3) + 1;
            if (dropChance == 1) {
                helm = new Helm(hero);
                artifactTextArea.setText(null);
                artifactTextArea.setText("New Helmet:");
                artifactTextArea.append("\n\nOld HP: " + hero.getHelmet().getHitPoints());
                artifactTextArea.append("\nNew HP: " + helm.getHitPoints());
            } else if (dropChance == 2) {
                armor = new Armor(hero);
                artifactTextArea.setText(null);
                artifactTextArea.setText("New Armor:");
                artifactTextArea.append("\n\nOld DEF: " + hero.getArmor().getDefense());
                artifactTextArea.append("\nNew DEF: " + armor.getDefense());
            } else if (dropChance == 3) {
                weapon = new Weapon(hero);
                artifactTextArea.setText(null);
                artifactTextArea.setText("New Weapon:");
                artifactTextArea.append("\n\nOld ATT: " + hero.getWeapon().getAttack());
                artifactTextArea.append("\nNew ATT: " + weapon.getAttack());
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        equipButton = new javax.swing.JButton();
        declineButton = new javax.swing.JButton();
        artifactScrollPane = new javax.swing.JScrollPane();
        artifactTextArea = new javax.swing.JTextArea();

        equipButton.setText("Equip");
        equipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipButtonActionPerformed(evt);
            }
        });

        declineButton.setText("Decline");
        declineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declineButtonActionPerformed(evt);
            }
        });

        artifactTextArea.setColumns(20);
        artifactTextArea.setRows(5);
        artifactScrollPane.setViewportView(artifactTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(equipButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(declineButton, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(75, 75, 75))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(artifactScrollPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(artifactScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(equipButton)
                .addGap(18, 18, 18)
                .addComponent(declineButton)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void declineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineButtonActionPerformed
        // TODO add your handling code here:
        this.firePropertyChange("Decline", null, evt);
    }//GEN-LAST:event_declineButtonActionPerformed

    private void equipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipButtonActionPerformed
        // TODO add your handling code here:
        if (dropChance == 1)
            StartGame.setHelm(helm);
        else if (dropChance == 2)
            StartGame.setArmor(armor);
        else if (dropChance == 3)
            StartGame.setWeapon(weapon);
        this.firePropertyChange("Equip", null, evt);
    }//GEN-LAST:event_equipButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane artifactScrollPane;
    private javax.swing.JTextArea artifactTextArea;
    private javax.swing.JButton declineButton;
    private javax.swing.JButton equipButton;
    // End of variables declaration//GEN-END:variables
}
