/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Panels;

import Model.Characters.Hero;

/**
 *
 * @author spencer
 */
public class CreateHero extends javax.swing.JPanel {

    private static Hero hero;
    private String name;
    private String type;

    /**
     * Creates new form CreateCharacter
     */
    public CreateHero() {
        initComponents();
        hero = null;
        name = null;
        type = null;
    }

    public static Hero getHero() {
        return hero;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        heroNameField = new javax.swing.JTextField();
        selectClassComboBox = new javax.swing.JComboBox<>();
        heroInfoArea = new javax.swing.JTextArea();
        nameLabel = new javax.swing.JLabel();

        CreateButton.setFont(new java.awt.Font("Courier", 0, 13)); // NOI18N
        CreateButton.setText("Create");
        CreateButton.setMaximumSize(new java.awt.Dimension(165, 30));
        CreateButton.setMinimumSize(new java.awt.Dimension(165, 30));
        CreateButton.setPreferredSize(new java.awt.Dimension(165, 30));
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Courier", 0, 13)); // NOI18N
        backButton.setText("Back");
        backButton.setMaximumSize(new java.awt.Dimension(165, 30));
        backButton.setMinimumSize(new java.awt.Dimension(165, 30));
        backButton.setPreferredSize(new java.awt.Dimension(165, 30));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        heroNameField.setFont(new java.awt.Font("Courier", 0, 13)); // NOI18N
        heroNameField.setToolTipText("Press Enter to apply name.");
        heroNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heroNameFieldActionPerformed(evt);
            }
        });

        selectClassComboBox.setFont(new java.awt.Font("Courier", 0, 13)); // NOI18N
        selectClassComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Class", "Warrior", "Archer" }));
        selectClassComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectClassComboBoxActionPerformed(evt);
            }
        });

        heroInfoArea.setColumns(20);
        heroInfoArea.setFont(new java.awt.Font("Courier", 0, 13)); // NOI18N
        heroInfoArea.setRows(5);
        heroInfoArea.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nameLabel.setFont(new java.awt.Font("Courier", 0, 13)); // NOI18N
        nameLabel.setText("Enter Hero Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(heroInfoArea, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(heroNameField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectClassComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(275, 275, 275))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(heroNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selectClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(heroInfoArea, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(CreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
        // TODO add your handling code here:
        if (selectClassComboBox.getSelectedItem() == "Select Class") {
            this.firePropertyChange("Default", null, evt);
        } else {
            if (name == null) {
                this.firePropertyChange("nullName", null, evt);
            } else if (type == null) {
                this.firePropertyChange("nullType", null, evt);
            } else {
                hero = new Hero(name, type);
                this.firePropertyChange("Load", null, evt);
            }
        }
    }//GEN-LAST:event_CreateButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.firePropertyChange("Back", null, evt);
    }//GEN-LAST:event_backButtonActionPerformed

    private void selectClassComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectClassComboBoxActionPerformed
        // TODO add your handling code here:
        heroInfoArea.setText(null);
        if (selectClassComboBox.getSelectedItem() == "Warrior") {
            heroInfoArea.setText("Base Attributes:\n\n");
            heroInfoArea.append("DEF: +20\n");
            heroInfoArea.append("HP : +50\n");
            type = "Warrior";
        } else if (selectClassComboBox.getSelectedItem() == "Archer") {
            heroInfoArea.setText("Base Attributes:\n\n");
            heroInfoArea.append("ATT: +20");
            type = "Archer";
        }
    }//GEN-LAST:event_selectClassComboBoxActionPerformed

    private void heroNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heroNameFieldActionPerformed
        // TODO add your handling code here:
        name = heroNameField.getText();
        //System.out.println(name);
    }//GEN-LAST:event_heroNameFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateButton;
    private javax.swing.JButton backButton;
    private javax.swing.JTextArea heroInfoArea;
    private javax.swing.JTextField heroNameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JComboBox<String> selectClassComboBox;
    // End of variables declaration//GEN-END:variables
}
